#=====================================================
# File: falsh-display-summary-settings.yaml
# Version 1.0.0
# Author: Kevin Thiel
# Creation Date: February 2024
# Description:
# This settings file is meant to be adaptable for any case
# study that needs a plot of the entire first flash event
# 
# Change log:
#  
#=====================================================


available-cases: ['20220322-perils','20220423-oklma']

#Output Data Locations
out_data_loc: '/localdata/first-flash/data/cases/'
out_plot_loc: '/localdata/first-flash/figures/cases/'


20220322-perils:
    
    case_name: 'PERiLS'
    #Input Data Locations
    glm_east_ff_loc: '/localdata/first-flash/data/GLM16-ff-processed/GLM16_first-flash-data-land_v2_s202203220000_e202203240000_c202401191535.nc'
    glm_west_ff_loc: '/localdata/first-flash/data/GLM17-ff-processed/GLM17_first-flash-data-land_v2_s202203220000_e202203240000_c202401191540.nc'
    lma_flash_loc: '/localdata/first-flash/data/perils-LMA-RAW/20220322/perils-LMA_RAW-flash_202203220000_c202401191517_source-min-10.csv'
    lma_event_loc: '/localdata/first-flash/data/perils-LMA-RAW/20220322/perils-LMA_RAW-event_202203220000_c202401191517_source-min-10.csv'
    lma_station_loc: '/localdata/first-flash/data/LMA-clusters/perils-LMA-20220322-stations.csv'
    
    
    f1: #Case Number
        
        #Search-specific data
        start_time: '2022-03-22T20:06:44.2'
        end_time: '2022-03-22T20:06:47.1'
        search_bounds: [-89.0,-87.5,32.7,34.2] #LONMIN, LONMAX, LATMIN, LATMAX (MUST MAKE A SQUARE)
        plot_bounds: [-90.0,-86,31,35] #LONMIN, LONMAX, LATMIN, LATMAX (MUST MAKE A SQUARE)
        hist_max : 60 #Maximum for the GLM group density y-axis
        
        #The correct ENI data
        eni_loc: '/localdata/first-flash/data/ENI-base-stock/eni_flash_flash20220322.csv'
       
    f2: #Case Number
        
        #Search-specific data
        start_time: '2022-03-23T02:43:18.8'
        end_time: '2022-03-23T02:43:19.3'
        search_bounds: [-88.3,-88.0,33.0,33.3] #LONMIN, LONMAX, LATMIN, LATMAX (MUST MAKE A SQUARE)
        plot_bounds: [-90.0,-86,31,35] #LONMIN, LONMAX, LATMIN, LATMAX (MUST MAKE A SQUARE)
        hist_max: 14 #Maximum for the GLM group density y-axis
        
        #The correct ENI data
        eni_loc: '/localdata/first-flash/data/ENI-base-stock/eni_flash_flash20220323.csv'

    f3.1: #Case Number
        
        #Search-specific data
        start_time: '2022-03-23T02:06:37.7'
        end_time: '2022-03-23T02:06:37.9'
        search_bounds: [-88.8,-88.5,32.3,32.6] #LONMIN, LONMAX, LATMIN, LATMAX (MUST MAKE A SQUARE)
        plot_bounds: [-90.0,-86,31,35] #LONMIN, LONMAX, LATMIN, LATMAX (MUST MAKE A SQUARE)
        hist_max: 5 #Maximum for the GLM group density y-axis
        
        #The correct ENI data
        eni_loc: '/localdata/first-flash/data/ENI-base-stock/eni_flash_flash20220323.csv'

    f3.2: #Case Number
        
        #Search-specific data
        start_time: '2022-03-23T02:14:06.8'
        end_time: '2022-03-23T02:14:07.2'
        search_bounds: [-88.9,-88.3,32.2,32.8] #LONMIN, LONMAX, LATMIN, LATMAX (MUST MAKE A SQUARE)
        plot_bounds: [-90.0,-86,31,35] #LONMIN, LONMAX, LATMIN, LATMAX (MUST MAKE A SQUARE)
        hist_max: 12 #Maximum for the GLM group density y-axis
        
        #The correct ENI data
        eni_loc: '/localdata/first-flash/data/ENI-base-stock/eni_flash_flash20220323.csv'

    f4: #Case Number
        
        #Search-specific data
        start_time: '2022-03-22T22:38:22.3'
        end_time: '2022-03-22T22:38:26.3'
        search_bounds: [-89.6,-87.9,32.8,34.5] #LONMIN, LONMAX, LATMIN, LATMAX (MUST MAKE A SQUARE)
        plot_bounds: [-90.0,-86,31,35] #LONMIN, LONMAX, LATMIN, LATMAX (MUST MAKE A SQUARE)
        hist_max: 50 #Maximum for the GLM group density y-axis
        
        #The correct ENI data
        eni_loc: '/localdata/first-flash/data/ENI-base-stock/eni_flash_flash20220322.csv'

20220423-oklma:
    case_name: 'OK-LMA'
    #Input Data Locations
    glm_east_ff_loc: '/localdata/first-flash/data/GLM16-ff-processed/GLM16_first-flash-data-land_v2_s202204230000_e202204250000_c202402281302.nc'
    glm_west_ff_loc: '/localdata/first-flash/data/GLM17-ff-processed/GLM17_first-flash-data-land_v2_s202204230000_e202204250000_c202402281302.nc'
    lma_flash_loc: '/localdata/first-flash/data/OK-LMA-RAW/20220423/OK-LMA_RAW-flash_202204230000_c202403141024_source-min-10.csv'
    lma_event_loc: '/localdata/first-flash/data/OK-LMA-RAW/20220423/OK-LMA_RAW-event_202204230000_c202403141024_source-min-10.csv'
    lma_station_loc: '/localdata/first-flash/data/LMA-clusters/OK-LMA-20220423-stations.csv'

    f1.1: #Case Number
        
        #Search-specific data
        start_time: '2022-04-23T22:07:43.45'
        end_time: '2022-04-23T22:07:43.75'
        search_bounds: [-98.3,-97.95,35.4,35.75] #LONMIN, LONMAX, LATMIN, LATMAX (MUST MAKE A SQUARE)
        plot_bounds: [-99.0,-96.5,34,36.5] #LONMIN, LONMAX, LATMIN, LATMAX (MUST MAKE A SQUARE)
        hist_max : 4 #Maximum for the GLM group density y-axis
        
        #The correct ENI data
        eni_loc: '/localdata/first-flash/data/ENI-base-stock/eni_flash_flash20220423.csv'

    f1.2: #Case Number
        
        #Search-specific data
        start_time: '2022-04-23T22:11:15.0'
        end_time: '2022-04-23T22:11:30.0'
        search_bounds: [-98.3,-97.95,35.4,35.75] #LONMIN, LONMAX, LATMIN, LATMAX (MUST MAKE A SQUARE)
        plot_bounds: [-99.0,-96.5,34,36.5] #LONMIN, LONMAX, LATMIN, LATMAX (MUST MAKE A SQUARE)
        hist_max : 4 #Maximum for the GLM group density y-axis
        
        #The correct ENI data
        eni_loc: '/localdata/first-flash/data/ENI-base-stock/eni_flash_flash20220423.csv'
 
      
