#=====================================================
# File: case-settings-manual-analysis-v1.yaml
# Version 1.0.0
# Author: Kevin Thiel
# Creation Date: June 2024
# Description:
# This settings file provides information for each case
# that is included in the manual analysis to create a 
# statistically robust sample.
# 
# Change log:
#  
#=====================================================

cases: ['20220423-ok', '20220504-tx', '20220612-co', '20220614-ne', '20220921-ut', '20220625-tn']

20220423-ok:
  case_name: '20220423 Oklahoma Supercell Case'

  start_time: '20220423-2100'
  end_time: '20220424-0200'

  ul_lat: 37.39
  ul_lon: -101.03
  lr_lat: 31.97
  lr_lon: -94.11

20220504-tx:
  case_name: '20220504 Texas Supercell Case' 

  start_time: '20220504-1600'
  end_time: '20220505-0400'

  ul_lat: 37.00
  ul_lon: -103.00
  lr_lat: 31.97
  lr_lon: -95.14

20220612-co:
  case_name: '20220612 High Plains Case'

  start_time: '20220612-1900'
  end_time: '20220613-0300'

  ul_lat: 45.85
  ul_lon: -109.05
  lr_lat: 37.00
  lr_lon: -97.27

20220614-ne:
  case_name: '20220614 Central Plains Case'

  start_time: '20220614-2200'
  end_time: '20220615-0600'

  ul_lat: 43.25
  ul_lon: -109.05
  lr_lat: 37.32
  lr_lon: -91.12

20220921-ut:
  case_name: '20220921 Intermountain West Case'

  start_time: '20220921-1600'
  end_time: '20220922-0400'

  ul_lat: 44.67
  ul_lon: -116.98
  lr_lat: 39.59
  lr_lon: -109.10

20220625-tn:
  case_name: '20220625 Tennessee Valley Case'

  start_time: '20220625-1500'
  end_time: '20220626-0100'

  ul_lat: 38.29
  ul_lon: -85.78
  lr_lat: 35.17
  lr_lon: -80.94